# Generated by Django 4.2.21 on 2025-06-07 01:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('direccion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Almacen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.BigIntegerField(blank=True, default=None, null=True)),
                ('updated_at', models.BigIntegerField(blank=True, default=None, null=True)),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre')),
                ('status', models.CharField(choices=[('ACT', 'Activo'), ('INA', 'Inactivo')], default='ACT', max_length=3, verbose_name='Estado')),
                ('codigo', models.CharField(max_length=20, null=True, unique=True, verbose_name='Código')),
                ('telefono', models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono')),
                ('comentarios', models.TextField(blank=True, null=True, verbose_name='Comentarios')),
                ('info_extra', models.TextField(blank=True, null=True, verbose_name='Información Extra')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s_set', to=settings.AUTH_USER_MODEL)),
                ('encargado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='almacen_encargado', to=settings.AUTH_USER_MODEL, verbose_name='Encargado')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)s_set', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.BigIntegerField(blank=True, default=None, null=True)),
                ('updated_at', models.BigIntegerField(blank=True, default=None, null=True)),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s_set', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)s_set', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.BigIntegerField(blank=True, default=None, null=True)),
                ('updated_at', models.BigIntegerField(blank=True, default=None, null=True)),
                ('status', models.CharField(choices=[('ACT', 'Activo'), ('INA', 'Inactivo')], default='ACT', max_length=3, verbose_name='Estado')),
                ('codigo', models.CharField(max_length=20, null=True, unique=True, verbose_name='Código')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre')),
                ('apellidos', models.CharField(blank=True, max_length=200, null=True, verbose_name='Apellidos')),
                ('telefono', models.CharField(blank=True, max_length=15, null=True, verbose_name='Teléfono')),
                ('email', models.EmailField(blank=True, max_length=150, null=True, verbose_name='Correo Electrónico')),
                ('tipo', models.IntegerField(choices=[(10, 'Potencial'), (20, 'Estándar'), (30, 'No Crédito'), (40, 'Crédito Semanal'), (50, 'Eventual'), (60, 'Buen Cliente'), (70, 'Premium')], default=20, verbose_name='Tipo de Cliente')),
                ('rfc', models.CharField(blank=True, max_length=15, null=True, verbose_name='RFC')),
                ('razon_social', models.CharField(blank=True, max_length=180, null=True, verbose_name='Razon social')),
                ('uso_cfdi', models.CharField(blank=True, max_length=100, null=True, verbose_name='Uso CFDI')),
                ('limite_credito', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Límite de crédito')),
                ('total_credito', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True, verbose_name='Total de crédito')),
                ('plazos_semanas', models.IntegerField(blank=True, default=0, null=True, verbose_name='Plazos en semanas')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s_set', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UnidadSAT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.BigIntegerField(blank=True, default=None, null=True)),
                ('updated_at', models.BigIntegerField(blank=True, default=None, null=True)),
                ('clave', models.CharField(max_length=10, unique=True, verbose_name='Clave')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s_set', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)s_set', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RegimenFiscal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.BigIntegerField(blank=True, default=None, null=True)),
                ('updated_at', models.BigIntegerField(blank=True, default=None, null=True)),
                ('codigo', models.CharField(max_length=20, unique=True, verbose_name='Código')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s_set', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)s_set', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.BigIntegerField(blank=True, default=None, null=True)),
                ('updated_at', models.BigIntegerField(blank=True, default=None, null=True)),
                ('origen', models.CharField(choices=[('MEX', 'México'), ('USA', 'Estados Unidos')], default='MEX', max_length=3, verbose_name='Origen')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre del Proveedor')),
                ('razon_social', models.CharField(blank=True, default=None, max_length=180, null=True, verbose_name='Razón Social')),
                ('rfc', models.CharField(max_length=13, verbose_name='RFC')),
                ('telefono', models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono')),
                ('correo', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Correo Electrónico')),
                ('status', models.CharField(choices=[('ACT', 'Activo'), ('INA', 'Inactivo')], default='ACT', max_length=3, verbose_name='Estado')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s_set', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)s_set', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.BigIntegerField(blank=True, default=None, null=True)),
                ('updated_at', models.BigIntegerField(blank=True, default=None, null=True)),
                ('status', models.CharField(choices=[('ACT', 'Activo'), ('INA', 'Inactivo')], default='ACT', max_length=3, verbose_name='Estado')),
                ('nombre', models.CharField(max_length=50)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='productos/')),
                ('precio_especial', models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='Precio Especial')),
                ('precio_sub_dist', models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='Precio Sub Distribuidor')),
                ('precio_mayoreo', models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='Precio Mayoreo')),
                ('precio_publico', models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='Precio Público')),
                ('clave_sat', models.CharField(blank=True, max_length=10, null=True, verbose_name='Clave SAT (Producto o Servicio)')),
                ('iva', models.DecimalField(decimal_places=2, default=0.16, max_digits=5)),
                ('ieps', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='productos', to='crm.categoria', verbose_name='Categoría')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s_set', to=settings.AUTH_USER_MODEL)),
                ('proveedores', models.ManyToManyField(to='crm.proveedor')),
                ('unidad_sat', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='crm.unidadsat', verbose_name='Unidad SAT')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)s_set', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Precio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.BigIntegerField(blank=True, default=None, null=True)),
                ('updated_at', models.BigIntegerField(blank=True, default=None, null=True)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tipo_precio', models.CharField(choices=[('ESP', 'Especial'), ('SUB', 'Subdistribuidor'), ('MAY', 'Mayoreo'), ('PUB', 'Público')], default='PUB', max_length=3)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s_set', to=settings.AUTH_USER_MODEL)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='precios', to='crm.producto')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)s_set', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Empresas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.BigIntegerField(blank=True, default=None, null=True)),
                ('updated_at', models.BigIntegerField(blank=True, default=None, null=True)),
                ('codigo', models.CharField(max_length=20, unique=True, verbose_name='Código')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s_set', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)s_set', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DireccionProveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calle', models.CharField(max_length=200)),
                ('numero_exterior', models.CharField(blank=True, max_length=20, null=True)),
                ('numero_interior', models.CharField(blank=True, max_length=20, null=True)),
                ('codigo_postal', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='direccion.codigopostal')),
                ('colonia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='direccion.colonia')),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='direccion.estado')),
                ('municipio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='direccion.municipio')),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='direccion_proveedor', to='crm.proveedor')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DireccionCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calle', models.CharField(max_length=200)),
                ('numero_exterior', models.CharField(blank=True, max_length=20, null=True)),
                ('numero_interior', models.CharField(blank=True, max_length=20, null=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='direccion_cliente', to='crm.cliente')),
                ('codigo_postal', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='direccion.codigopostal')),
                ('colonia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='direccion.colonia')),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='direccion.estado')),
                ('municipio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='direccion.municipio')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DireccionAlmacen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calle', models.CharField(max_length=200)),
                ('numero_exterior', models.CharField(blank=True, max_length=20, null=True)),
                ('numero_interior', models.CharField(blank=True, max_length=20, null=True)),
                ('almacen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='direccion_almacen', to='crm.almacen')),
                ('codigo_postal', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='direccion.codigopostal')),
                ('colonia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='direccion.colonia')),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='direccion.estado')),
                ('municipio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='direccion.municipio')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='cliente',
            name='regimen_fiscal',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cliente_regimen_fiscal', to='crm.regimenfiscal', verbose_name='Régimen Fiscal'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)s_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Agente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.BigIntegerField(blank=True, default=None, null=True)),
                ('updated_at', models.BigIntegerField(blank=True, default=None, null=True)),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre del Agente')),
                ('status', models.CharField(choices=[('ACT', 'Activo'), ('INA', 'Inactivo')], default='ACT', max_length=3, verbose_name='Estado')),
                ('codigo', models.CharField(max_length=20, null=True, unique=True, verbose_name='Código del Agente')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s_set', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)s_set', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
