# Generated by Django 4.2.21 on 2025-06-07 02:05

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Empresas',
            new_name='Empresa',
        ),
    ]
