# Generated by Django 4.2.21 on 2025-06-08 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_rename_empresas_empresa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='limite_credito',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=10, null=True, verbose_name='Límite de crédito'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='nombre',
            field=models.CharField(blank=True, default=None, max_length=200, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='razon_social',
            field=models.CharField(blank=True, max_length=180, null=True, verbose_name='Razón social'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='uso_cfdi',
            field=models.CharField(blank=True, default=None, max_length=100, null=True, verbose_name='Uso CFDI'),
        ),
    ]
