# Generated by Django 4.2.21 on 2025-06-05 00:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_cliente_alter_almacen_codigo_alter_almacen_encargado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='razon_social',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='crm.razonsocial'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='total_credito',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True, verbose_name='Total de crédito'),
        ),
    ]
