# Generated by Django 4.2.21 on 2025-06-08 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_alter_cliente_limite_credito_alter_cliente_nombre_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='proveedor',
            name='codigo',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='Código'),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='rfc',
            field=models.CharField(max_length=15, verbose_name='RFC'),
        ),
    ]
