# Generated by Django 4.2.21 on 2025-06-05 00:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0004_alter_cliente_razon_social_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='razon_social',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cliente_razon_social', to='crm.razonsocial', verbose_name='Razón Social'),
        ),
    ]
