# Generated by Django 4.2.21 on 2025-06-08 20:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0004_proveedor_codigo_alter_proveedor_rfc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='direccioncliente',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='direccion_proveedor', to='crm.cliente'),
        ),
    ]
