# Generated by Django 4.2.21 on 2025-06-08 20:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0005_alter_direccioncliente_cliente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='direccioncliente',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='direccion_cliente', to='crm.cliente'),
        ),
    ]
