# Generated by Django 4.2.21 on 2025-06-08 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0006_alter_direccioncliente_cliente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proveedor',
            name='origen',
            field=models.CharField(blank=True, choices=[('MEX', 'México'), ('USA', 'Estados Unidos')], default='MEX', max_length=3, null=True, verbose_name='Origen'),
        ),
    ]
