# Generated by Django 4.2.21 on 2025-06-08 21:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('direccion', '0001_initial'),
        ('crm', '0007_alter_proveedor_origen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='direccionalmacen',
            name='calle',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='direccionalmacen',
            name='codigo_postal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='direccion.codigopostal'),
        ),
        migrations.AlterField(
            model_name='direccionalmacen',
            name='colonia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='direccion.colonia'),
        ),
        migrations.AlterField(
            model_name='direccionalmacen',
            name='estado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='direccion.estado'),
        ),
        migrations.AlterField(
            model_name='direccionalmacen',
            name='municipio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='direccion.municipio'),
        ),
        migrations.AlterField(
            model_name='direccioncliente',
            name='calle',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='direccioncliente',
            name='codigo_postal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='direccion.codigopostal'),
        ),
        migrations.AlterField(
            model_name='direccioncliente',
            name='colonia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='direccion.colonia'),
        ),
        migrations.AlterField(
            model_name='direccioncliente',
            name='estado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='direccion.estado'),
        ),
        migrations.AlterField(
            model_name='direccioncliente',
            name='municipio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='direccion.municipio'),
        ),
        migrations.AlterField(
            model_name='direccionproveedor',
            name='calle',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='direccionproveedor',
            name='codigo_postal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='direccion.codigopostal'),
        ),
        migrations.AlterField(
            model_name='direccionproveedor',
            name='colonia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='direccion.colonia'),
        ),
        migrations.AlterField(
            model_name='direccionproveedor',
            name='estado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='direccion.estado'),
        ),
        migrations.AlterField(
            model_name='direccionproveedor',
            name='municipio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='direccion.municipio'),
        ),
    ]
