# Generated by Django 4.2.21 on 2025-06-08 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0008_alter_direccionalmacen_calle_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proveedor',
            name='rfc',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='RFC'),
        ),
    ]
