# Generated by Django 4.2.21 on 2025-06-09 02:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0009_alter_proveedor_rfc'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='codigo',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True, verbose_name='Código'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='productos_categoria', to='crm.categoria', verbose_name='Categoría'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='descripcion',
            field=models.TextField(blank=True, null=True, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='nombre',
            field=models.CharField(max_length=50, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='origen',
            field=models.CharField(blank=True, choices=[('MEX', 'México'), ('USA', 'Estados Unidos'), ('OTR', 'Otro')], default='MEX', max_length=3, null=True, verbose_name='Origen'),
        ),
    ]
