# Generated by Django 4.2.21 on 2025-06-09 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0010_producto_codigo_alter_producto_categoria_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='proveedores',
            field=models.ManyToManyField(blank=True, to='crm.proveedor'),
        ),
    ]
