# Generated by Django 4.2.21 on 2025-06-10 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0011_alter_producto_proveedores'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='stock',
            field=models.PositiveIntegerField(default=0, verbose_name='Stock Global'),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='descripcion',
            field=models.TextField(blank=True, null=True, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='nombre',
            field=models.CharField(max_length=50, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='ieps',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='IEPS'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='iva',
            field=models.DecimalField(decimal_places=2, default=0.16, max_digits=5, verbose_name='IVA'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='precio_especial',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True, verbose_name='Precio Especial'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='precio_mayoreo',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, null=True, verbose_name='Precio Mayoreo'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='precio_publico',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, null=True, verbose_name='Precio Público'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='precio_sub_dist',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, null=True, verbose_name='Precio Sub Distribuidor'),
        ),
    ]
