# Generated by Django 4.2.21 on 2025-06-18 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0012_producto_stock_alter_categoria_descripcion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='direccionalmacen',
            name='latitud',
            field=models.FloatField(blank=True, default=None, null=True, verbose_name='Latitud'),
        ),
        migrations.AddField(
            model_name='direccionalmacen',
            name='longitud',
            field=models.FloatField(blank=True, default=None, null=True, verbose_name='Longitud'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='stock',
            field=models.PositiveIntegerField(blank=True, default=0, verbose_name='Stock Global'),
        ),
    ]
