# Generated by Django 4.2.21 on 2025-06-18 03:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('direccion', '0001_initial'),
        ('crm', '0013_direccionalmacen_latitud_direccionalmacen_longitud_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agente',
            name='apellidos',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Apellidos'),
        ),
        migrations.AddField(
            model_name='agente',
            name='email',
            field=models.EmailField(blank=True, max_length=150, null=True, verbose_name='Correo Electrónico'),
        ),
        migrations.AddField(
            model_name='agente',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='agentes', verbose_name='Imagen'),
        ),
        migrations.AddField(
            model_name='agente',
            name='telefono',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Teléfono'),
        ),
        migrations.AlterField(
            model_name='agente',
            name='nombre',
            field=models.CharField(max_length=200, verbose_name='Nombres'),
        ),
        migrations.CreateModel(
            name='DireccionAgente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calle', models.CharField(blank=True, max_length=200, null=True)),
                ('numero_exterior', models.CharField(blank=True, max_length=20, null=True)),
                ('numero_interior', models.CharField(blank=True, max_length=20, null=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='direccion_agente', to='crm.agente')),
                ('codigo_postal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='direccion.codigopostal')),
                ('colonia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='direccion.colonia')),
                ('estado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='direccion.estado')),
                ('municipio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='direccion.municipio')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
