# Generated by Django 4.2.21 on 2025-06-19 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0015_alter_producto_stock'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='precio',
            name='precio',
        ),
        migrations.RemoveField(
            model_name='precio',
            name='producto',
        ),
        migrations.RemoveField(
            model_name='precio',
            name='tipo_precio',
        ),
        migrations.AddField(
            model_name='cliente',
            name='precio_tipo',
            field=models.CharField(choices=[('ESP', 'Especial'), ('SUB', 'Subdistribuidor'), ('MAY', 'Mayoreo'), ('PUB', 'Público')], default='PUB', max_length=4, verbose_name='Tipo de precio'),
        ),
    ]
