# Generated by Django 4.2.21 on 2025-06-23 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0016_remove_precio_precio_remove_precio_producto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='precio_tipo',
            field=models.CharField(choices=[('ESP', 'Especial'), ('SUB', 'Subdistribuidor'), ('MAY', 'Mayoreo'), ('PUB', 'Público')], default='PUB', max_length=4, verbose_name='Lista de precios'),
        ),
    ]
