from django.urls import path
from .views import (
    accordions_view,
    alerts_view,
    avatars_view,
    badges_view,
    breadcrumb_view,
    buttons_view,
    cards_view,
    carousel_view,
    collapse_view,
    dropdowns_view,
    embed_video_view,
    grid_view,
    list_group_view,
    modals_view,
    notifications_view,
    offcanvas_view,
    placeholder_view,
    pagination_view,
    popovers_view,
    progress_view,
    spinners_view,
    tabs_view,
    tooltips_view,
    typography_view,
    nestable_view,
    range_slider_view,
    tour_view,
    scrollbar_view,
    scrollspy_view,
    sweet_alert_view,
    widgets_view,
    two_tones_view,
    colored_view,
    feather_view,
    mdi_view,
    dripicons_view,
    font_awesome_view,
    remixicons_view,
    unicons_view,
    apex_view,
    flot_view,
    morris_view,
    chartjs_view,
    peity_view,
    chartist_view,
    c3_view,
    sparklines_view,
    jquery_knob_view,
    elements_view,
    advanced_view,
    validation_view,
    pickers_view,
    wizard_view,
    masks_view,
    file_uploads_view,
    editors_view,
    basic_view,
    datatables_view,
    editable_view,
    responsive_view,
    tablesaw_view,
    google_view,
    vector_view,
    mapael_view

)

urlpatterns = [
    # Base Ui
    path("ui/accordions", view=accordions_view, name="accordions"),
    path("ui/alerts", view=alerts_view, name="alerts"),
    path("ui/avatars", view=avatars_view, name="avatars"),
    path("ui/badges", view=badges_view, name="badges"),
    path("ui/breadcrumb", view=breadcrumb_view, name="breadcrumb"),
    path("ui/buttons", view=buttons_view, name="buttons"),
    path("ui/cards", view=cards_view, name="cards"),
    path("ui/carousel", view=carousel_view, name="carousel"),
    path("ui/collapse", view=collapse_view, name="collapse"),
    path("ui/dropdowns", view=dropdowns_view, name="dropdowns"),
    path("ui/embed-video", view=embed_video_view, name="embed-video"),
    path("ui/grid", view=grid_view, name="grid"),
    path("ui/list-group", view=list_group_view, name="list-group"),
    path("ui/modals", view=modals_view, name="modals"),
    path("ui/notifications", view=notifications_view, name="notifications"),
    path("ui/offcanvas", view=offcanvas_view, name="offcanvas"),
    path("ui/placeholders", view=placeholder_view, name="placeholders"),
    path("ui/pagination", view=pagination_view, name="pagination"),
    path("ui/popovers", view=popovers_view, name="popovers"),
    path("ui/progress", view=progress_view, name="progress"),
    path("ui/spinners", view=spinners_view, name="spinners"),
    path("ui/tabs", view=tabs_view, name="tabs"),
    path("ui/tooltips", view=tooltips_view, name="tooltips"),
    path("ui/typography", view=typography_view, name="typography"),

    #Extended UI
    path("extended/nestable", view=nestable_view, name="nestable"),
    path("extended/range-slider", view=range_slider_view, name="range-slider"),
    path("extended/tour", view=tour_view, name="tour"),
    path("extended/scrollbar", view=scrollbar_view, name="scrollbar"),
    path("extended/scrollspy", view=scrollspy_view, name="scrollspy"),
    path("extended/sweet-alert", view=sweet_alert_view, name="sweet-alert"),

    #Widgets
    path("widgets", view=widgets_view, name="widgets"),

    #Icons
    path("icons/tow-tones", view=two_tones_view, name="two-tones"),
    path("icons/colored", view=colored_view, name="colored"),
    path("icons/feather", view=feather_view, name="feather"),
    path("icons/mdi", view=mdi_view, name="mdi"),
    path("icons/dripicons", view=dripicons_view, name="dripicons"),
    path("icons/font-awesome", view=font_awesome_view, name="font-awesome"),
    path("icons/remixicons", view=remixicons_view, name="remixicons"),
    path("icons/unicons", view=unicons_view, name="unicons"),

    #Chartjs
    path("charts/apex", view=apex_view, name="apex"),
    path("charts/flot", view=flot_view, name="flot"),
    path("charts/morris", view=morris_view, name="morris"),
    path("charts/chartjs", view=chartjs_view, name="chartjs"),
    path("charts/peity", view=peity_view, name="peity"),
    path("charts/chartist", view=chartist_view, name="chartist"),
    path("charts/c3", view=c3_view, name="c3"),
    path("charts/sparklines", view=sparklines_view, name="sparklines"),
    path("charts/jquery-knob", view=jquery_knob_view, name="jquery-knob"),

    #Forms
    path("forms/elements", view=elements_view, name="elements"),
    path("forms/advanced", view=advanced_view, name="advanced"),
    path("forms/validation", view=validation_view, name="validation"),
    path("forms/pickers", view=pickers_view, name="pickers"),
    path("forms/wizard", view=wizard_view, name="wizard"),
    path("forms/masks", view=masks_view, name="masks"),
    path("forms/fileuploads", view=file_uploads_view, name="fileuploads"),
    path("forms/editors", view=editors_view, name="editors"),

    #Tables
    path("tables/basic", view=basic_view, name="basic"),
    path("tables/datatables", view=datatables_view, name="datatables"),
    path("tables/editable", view=editable_view, name="editable"),
    path("tables/responsive", view=responsive_view, name="responsive"),
    path("tables/tablesaw", view=tablesaw_view, name="tablesaw"),

   #Maps
   path("maps/google", view=google_view, name="google"),
   path("maps/vector", view=vector_view, name="vector"),
   path("maps/mapael", view=mapael_view, name="mapael")


]