# Generated by Django 4.2.21 on 2025-06-18 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_direccion'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='telefono',
            field=models.CharField(default=None, max_length=15, null=True, verbose_name='Teléfono'),
        ),
        migrations.AlterField(
            model_name='user',
            name='created_at',
            field=models.IntegerField(blank=True, default=True, null=True, verbose_name='Fecha de creación'),
        ),
    ]
